CREATE TABLE IF NOT EXISTS `Agent_visible` (
  `AgentIdentifier` INT PRIMARY KEY COMMENT 'Agent Identifier',
  `AgentOfficeID` INT COMMENT 'Agent Office ID',
  `DateAssignedtoOffice` DATE default '0000-00-00' NOT NULL COMMENT 'Date Assigned to Office',
  `AgentLogonName` TEXT COMMENT 'Agent Logon Name',
  `AgentPassword` TEXT COMMENT 'Agent Password',
  `SecurityLevel` INT COMMENT 'Security Level',
  `AgentType` VARCHAR(50) COMMENT 'Agent Type',
  `DateAgentTypeChanged` DATE default '0000-00-00' NOT NULL COMMENT 'Date Agent Type Changed',
  `AgentDesignation` TEXT COMMENT 'Agent Designation',
  `AgentSalutation` TEXT COMMENT 'Agent Salutation',
  `AgentFirstName` TEXT COMMENT 'Agent First Name',
  `AgentLastName` TEXT COMMENT 'Agent Last Name',
  `AgentMiddleInitial` TEXT COMMENT 'Agent Middle Initial',
  `AgentAddressStreetName` TEXT COMMENT 'Agent Address Street Name',
  `AgentAddress2` TEXT COMMENT 'Agent Address2',
  `AgentCity` TEXT COMMENT 'Agent City',
  `AgentState` VARCHAR(50) COMMENT 'Agent State',
  `AgentZip` TEXT COMMENT 'Agent Zip',
  `AgentMailStreetName` TEXT COMMENT 'Agent Mail Street Name',
  `AgentMailAddress2` TEXT COMMENT 'Agent Mail Address2',
  `AgentMailCity` TEXT COMMENT 'Agent Mail City',
  `AgentMailState` VARCHAR(50) COMMENT 'Agent Mail State',
  `AgentMailZip` TEXT COMMENT 'Agent Mail Zip',
  `AgentPhone1Description` TEXT COMMENT 'Agent Phone1 Description',
  `AgentPhone1CountryId` VARCHAR(50) COMMENT 'Agent Phone1 CountryId',
  `AgentPhone1Number` TEXT COMMENT 'Agent Phone1 Number',
  `AgentPhone1Extension` TEXT COMMENT 'Agent Phone1 Extension',
  `AgentPhone2Description` TEXT COMMENT 'Agent Phone2 Description',
  `AgentPhone2CountryId` VARCHAR(50) COMMENT 'Agent Phone2 CountryId',
  `AgentPhone2Number` TEXT COMMENT 'Agent Phone2 Number',
  `AgentPhone2Extension` TEXT COMMENT 'Agent Phone2 Extension',
  `AgentPhone3Description` TEXT COMMENT 'Agent Phone3 Description',
  `AgentPhone3CountryId` VARCHAR(50) COMMENT 'Agent Phone3 CountryId',
  `AgentPhone3Number` TEXT COMMENT 'Agent Phone3 Number',
  `AgentPhone3Extension` TEXT COMMENT 'Agent Phone3 Extension',
  `AgentPhone4Description` TEXT COMMENT 'Agent Phone4 Description',
  `AgentPhone4CountryId` VARCHAR(50) COMMENT 'Agent Phone4 CountryId',
  `AgentPhone4Number` TEXT COMMENT 'Agent Phone4 Number',
  `AgentPhone4Extension` TEXT COMMENT 'Agent Phone4 Extension',
  `AgentPhone5Description` TEXT COMMENT 'Agent Phone5 Description',
  `AgentPhone5CountryId` VARCHAR(50) COMMENT 'Agent Phone5 CountryId',
  `AgentPhone5Number` TEXT COMMENT 'Agent Phone5 Number',
  `AgentPhone5Extension` TEXT COMMENT 'Agent Phone5 Extension',
  `AgentEmail` TEXT COMMENT 'Agent Email',
  `AgentUrl` TEXT COMMENT 'Agent Url',
  `StateAgentIsMemberOf` VARCHAR(50) COMMENT 'State Agent Is Member Of',
  `DateofAgtStateMbrshp` DATE default '0000-00-00' NOT NULL COMMENT 'Date of Agt State Mbrshp',
  `DuesPaidtoBoard` VARCHAR(50) COMMENT 'Dues Paid to Board',
  `BoardDuesPaidThrough` TEXT COMMENT 'Board Dues Paid Through',
  `AgentStatus` VARCHAR(50) COMMENT 'Agent Status',
  `StatusDate` DATE default '0000-00-00' NOT NULL COMMENT 'Status Date',
  `AgentTraining` VARCHAR(50) COMMENT 'Agent Training',
  `TrainingDate` DATE default '0000-00-00' NOT NULL COMMENT 'Training Date',
  `AgentLicenseID` TEXT COMMENT 'Agent License ID',
  `AgentLicenseDate` DATE default '0000-00-00' NOT NULL COMMENT 'Agent License Date',
  `SpouseFirstName` TEXT COMMENT 'Spouse First Name',
  `AgentMailPreference` VARCHAR(50) COMMENT 'Agent Mail Preference',
  `AgentBirthDate` DATE default '0000-00-00' NOT NULL COMMENT 'Agent Birth Date',
  `LockBoxNumber` TEXT COMMENT 'Lock Box Number',
  `DateKeyAssigned` DATE default '0000-00-00' NOT NULL COMMENT 'Date Key Assigned',
  `PreviousKeyNumber` TEXT COMMENT 'Previous Key Number',
  `Keys` INT COMMENT 'Number of Keys',
  `LockBoxKeyDeposit` DECIMAL(10,2) COMMENT 'Lock Box Key Deposit',
  `ActiveBookCount` INT COMMENT 'Active Book Count',
  `SoldBookCount` INT COMMENT 'Sold Book Count',
  `CorpPACContributionYTD` DECIMAL(10,2) COMMENT 'Corp PAC Contribution YTD',
  `PersPACContributionYTD` DECIMAL(10,2) COMMENT 'Pers PAC Contribution YTD',
  `LstPACContributionDate` DATE default '0000-00-00' NOT NULL COMMENT 'Lst PAC Contribution Date',
  `LstPACContribCheck` TEXT COMMENT 'Lst PAC Contrib Check #',
  `PrevYearPACContribute` DECIMAL(10,2) COMMENT 'Prev Year PAC Contribute',
  `DistributedUser` VARCHAR(50) COMMENT 'Distributed User',
  `LastTriggerDate` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'Last Trigger Date',
  `UserPhotosCode` VARCHAR(50) COMMENT 'User Photos Code',
  `UpdateDate` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'Update Date',
  `UpdateByAgent` INT COMMENT 'Update By Agent',
  `DateAdded` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'Date Added',
  `MultipleLogon` VARCHAR(50) COMMENT 'Multiple Logon',
  `Hash` TEXT COMMENT 'Hash',
  `Photographer` TEXT COMMENT 'Photographer',
  `Active` VARCHAR(50) COMMENT 'Active',
  `UserCode` TEXT COMMENT 'User Code',
  `NRDSID` TEXT COMMENT 'NRDS_ID',
  `BoardUserID` INT COMMENT 'Board User ID',
  `AOMainOfficeID` INT COMMENT 'AOMain Office ID',
  `AOOfficeType` VARCHAR(50) COMMENT 'AOOffice Type',
  `AOOfficeAbbreviation` TEXT COMMENT 'AOOffice Abbreviation',
  `AOOfficeName` TEXT COMMENT 'AOOffice Name',
  `AOOffceAddressStreetName` TEXT COMMENT 'AOOffce Address Street Name',
  `AOOfficeAddress2` TEXT COMMENT 'AOOffice Address2',
  `AOOfficeCity` TEXT COMMENT 'AOOffice City',
  `AOOfficeState` VARCHAR(50) COMMENT 'AOOffice State',
  `AOOfficeZip` TEXT COMMENT 'AOOffice Zip',
  `AOOfficePhone1Description` TEXT COMMENT 'AOOffice Phone1 Description',
  `AOOfficePhone1CountryId` VARCHAR(50) COMMENT 'AOOffice Phone1 CountryId',
  `AOOfficePhone1Number` TEXT COMMENT 'AOOffice Phone1 Number',
  `AOOfficePhone1Extension` TEXT COMMENT 'AOOffice Phone1 Extension',
  `AOOfficeEmail` TEXT COMMENT 'AOOffice Email',
  `AOOfficeUrl` TEXT COMMENT 'AOOffice Url',
  `AOBoardID` INT COMMENT 'AOBoard ID',
  `UPPreferredPhone` INT COMMENT 'UPPreferred Phone',
  `UPAgentimageTimestamp` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'UPAgent image Timestamp',
  `UPLogoimageTimestamp` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'UPLogo image Timestamp'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT 'All Agents - All Agents (Visible Names)';