CREATE TABLE IF NOT EXISTS `Hotsheet_RE_1_visible` (
  `SystemID` INT COMMENT 'SystemID',
  `Class` VARCHAR(50) COMMENT 'Class',
  `Type` VARCHAR(50) COMMENT 'Type',
  `Area` VARCHAR(50) COMMENT 'Area',
  `AddressNumber` TEXT COMMENT 'Address Number',
  `AddressSearchNumber` INT COMMENT 'Address Search Number',
  `AddressDirection` TEXT COMMENT 'Address Direction',
  `AddressStreet` TEXT COMMENT 'Address Street',
  `Address2` TEXT COMMENT 'Address 2',
  `City` TEXT COMMENT 'City',
  `State` VARCHAR(50) COMMENT 'State',
  `Zip` TEXT COMMENT 'Zip',
  `StatusCategory` VARCHAR(50) COMMENT 'Status Category',
  `StatusDetail` TEXT COMMENT 'Status Detail',
  `SearchPrice` INT COMMENT 'Search Price',
  `Agent` INT COMMENT 'Agent',
  `ListingOffice1` INT COMMENT 'Listing Office 1',
  `ListingAgent2` INT COMMENT 'Listing Agent 2',
  `ListingOffice2` INT COMMENT 'Listing Office 2',
  `StatusDate` DATE default '0000-00-00' NOT NULL COMMENT 'Status Date',
  `UpdateDate` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'Update Date',
  `MLS` TEXT COMMENT 'MLS #',
  `StreetDesignation` VARCHAR(50) COMMENT 'Street Designation',
  `GeoLatitude` DECIMAL(10,2) COMMENT 'Geo Latitude',
  `GeoLongitude` DECIMAL(10,2) COMMENT 'Geo Longitude',
  `GeoQuality` DECIMAL(10,2) COMMENT 'Geo Quality',
  `GeoZoomLevel` DECIMAL(10,2) COMMENT 'Geo Zoom Level',
  `GeoAddressLine` TEXT COMMENT 'Geo Address Line',
  `GeoPrimaryCity` TEXT COMMENT 'Geo Primary City',
  `GeoSecondaryCity` TEXT COMMENT 'Geo Secondary City',
  `GeoSubdivision` TEXT COMMENT 'Geo Subdivision',
  `GeoPostalCode` TEXT COMMENT 'Geo Postal Code',
  `GeoMatchCode` INT COMMENT 'Geo Match Code',
  `GeoMatchedMethod` INT COMMENT 'Geo Matched Method',
  `GeoUpdateTimestamp` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'Geo Update Timestamp',
  `Address` TEXT COMMENT 'Address',
  `Status` VARCHAR(50) COMMENT 'Status',
  `HotsheetID` INT PRIMARY KEY COMMENT 'Hotsheet ID',
  `HotsheetType` VARCHAR(50) COMMENT 'Hotsheet Type',
  `HotsheetTimestamp` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'Hotsheet Timestamp',
  `Comment` TEXT COMMENT 'Comment',
  `HotsheetStatusID` VARCHAR(50) COMMENT 'Hotsheet Status ID',
  `HotsheetPreviousPrice` INT COMMENT 'Hotsheet Previous Price',
  `HotsheetPrice` INT COMMENT 'Hotsheet Price',
  `VOWInclude` VARCHAR(50) COMMENT 'VOW Include',
  `VOWAddress` VARCHAR(50) COMMENT 'VOW Address',
  `VOWComment` VARCHAR(50) COMMENT 'VOW Comment',
  `VOWAVM` VARCHAR(50) COMMENT 'VOW AVM',
  `IDXInclude` VARCHAR(50) COMMENT 'IDX Include',
  `DocTimestamp` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'Doc Timestamp'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT 'Hotsheet - RESIDENTIAL (Visible Names)';