CREATE TABLE IF NOT EXISTS `Office_visible` (
  `OfficeIdentifier` INT PRIMARY KEY COMMENT 'Office Identifier',
  `MainOfficeID` INT COMMENT 'Main Office ID',
  `OfficeType` VARCHAR(50) COMMENT 'Office Type',
  `OfficeAbbreviation` TEXT COMMENT 'Office Abbreviation',
  `OfficeName` TEXT COMMENT 'Office Name',
  `OffceAddressStreetName` TEXT COMMENT 'Offce Address Street Name',
  `OfficeAddress2` TEXT COMMENT 'Office Address2',
  `OfficeCity` TEXT COMMENT 'Office City',
  `OfficeState` VARCHAR(50) COMMENT 'Office State',
  `OfficeZip` TEXT COMMENT 'Office Zip',
  `OfficeMailStreetName` TEXT COMMENT 'Office Mail Street Name',
  `OfficeMailAddress2` TEXT COMMENT 'Office Mail Address2',
  `OfficeMailCity` TEXT COMMENT 'Office Mail City',
  `OfficeMailState` VARCHAR(50) COMMENT 'Office Mail State',
  `OfficeMailZip` TEXT COMMENT 'Office Mail Zip',
  `OfficeContact` TEXT COMMENT 'Office Contact',
  `OfficePhone1Description` TEXT COMMENT 'Office Phone1 Description',
  `OfficePhone1CountryId` VARCHAR(50) COMMENT 'Office Phone1 CountryId',
  `OfficePhone1Number` TEXT COMMENT 'Office Phone1 Number',
  `OfficePhone1Extension` TEXT COMMENT 'Office Phone1 Extension',
  `OfficePhone2Description` TEXT COMMENT 'Office Phone2 Description',
  `OfficePhone2CountryId` VARCHAR(50) COMMENT 'Office Phone2 CountryId',
  `OfficePhone2Number` TEXT COMMENT 'Office Phone2 Number',
  `OfficePhone2Extension` TEXT COMMENT 'Office Phone2 Extension',
  `OfficePhone3Description` TEXT COMMENT 'Office Phone3 Description',
  `OfficePhone3CountryId` VARCHAR(50) COMMENT 'Office Phone3 CountryId',
  `OfficePhone3Number` TEXT COMMENT 'Office Phone3 Number',
  `OfficePhone3Extension` TEXT COMMENT 'Office Phone3 Extension',
  `OfficeEmail` TEXT COMMENT 'Office Email',
  `OfficeUrl` TEXT COMMENT 'Office Url',
  `NationalRDSNumber` TEXT COMMENT 'National RDS Number',
  `DesignatedBrokerID` INT COMMENT 'Designated Broker ID',
  `BrokerManagementReports` VARCHAR(50) COMMENT 'Broker Management Reports',
  `BookRouteID` TEXT COMMENT 'Book Route ID',
  `BookRouteSequence` TEXT COMMENT 'Book Route Sequence',
  `ActiveBookCount` INT COMMENT 'Active Book Count',
  `SoldBookCount` INT COMMENT 'Sold Book Count',
  `BoardMember` VARCHAR(50) COMMENT 'Board Member',
  `MLSMember` VARCHAR(50) COMMENT 'MLS Member',
  `CommercialInvestmentDiv` VARCHAR(50) COMMENT 'Commercial Investment Div',
  `Affiliate` VARCHAR(50) COMMENT 'Affiliate',
  `PrintOnMailingLists` VARCHAR(50) COMMENT 'Print On Mailing Lists',
  `OfficeComputerAccess` VARCHAR(50) COMMENT 'Office Computer Access',
  `NationalDuesAnnual` DECIMAL(10,2) COMMENT 'National Dues Annual',
  `NationalDuesPaid` VARCHAR(50) COMMENT 'National Dues Paid',
  `StateDuesAnnual` DECIMAL(10,2) COMMENT 'State Dues Annual',
  `StateDuesPaid` VARCHAR(50) COMMENT 'State Dues Paid',
  `LocalDuesAnnual` DECIMAL(10,2) COMMENT 'Local Dues Annual',
  `LocalDuesPaid` VARCHAR(50) COMMENT 'Local Dues Paid',
  `MLSFeesMonthly` DECIMAL(10,2) COMMENT 'MLS Fees Monthly',
  `MLSFeesPaid` VARCHAR(50) COMMENT 'MLS Fees Paid',
  `NationalNonMemberCharge` DECIMAL(10,2) COMMENT 'National NonMember Charge',
  `StateNonMemberCharge` DECIMAL(10,2) COMMENT 'State NonMember Charge',
  `LocalNonMemberCharge` DECIMAL(10,2) COMMENT 'Local NonMember Charge',
  `CorpPACContribution` DECIMAL(10,2) COMMENT 'Corp PAC Contribution',
  `LstPACContributionDate` DATE default '0000-00-00' NOT NULL COMMENT 'Lst PAC Contribution Date',
  `LstPACContribCheck` TEXT COMMENT 'Lst PAC Contrib Check #',
  `PreviousPACContribution` DECIMAL(10,2) COMMENT 'Previous PAC Contribution',
  `UpdateDate` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'Update Date',
  `UpdateByAgent` INT COMMENT 'Update By Agent',
  `DateAdded` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'Date Added',
  `BoardID` INT COMMENT 'Board ID',
  `IDXInclude` CHAR(1) COMMENT 'IDX Include',
  `MOOfficeType` VARCHAR(50) COMMENT 'MOOffice Type',
  `MOOfficeAbbreviation` TEXT COMMENT 'MOOffice Abbreviation',
  `MOOfficeName` TEXT COMMENT 'MOOffice Name',
  `MOOffceAddressStreetName` TEXT COMMENT 'MOOffce Address Street Name',
  `MOOfficeAddress2` TEXT COMMENT 'MOOffice Address2',
  `MOOfficeCity` TEXT COMMENT 'MOOffice City',
  `MOOfficeState` VARCHAR(50) COMMENT 'MOOffice State',
  `MOOfficeZip` TEXT COMMENT 'MOOffice Zip',
  `MOOfficePhone1Description` TEXT COMMENT 'MOOffice Phone1 Description',
  `MOOfficePhone1CountryId` VARCHAR(50) COMMENT 'MOOffice Phone1 CountryId',
  `MOOfficePhone1Number` TEXT COMMENT 'MOOffice Phone1 Number',
  `MOOfficePhone1Extension` TEXT COMMENT 'MOOffice Phone1 Extension',
  `MOOfficeEmail` TEXT COMMENT 'MOOffice Email',
  `MOOfficeUrl` TEXT COMMENT 'MOOffice Url',
  `MOBoardID` INT COMMENT 'MOBoard ID'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT 'Offices - Offices (Visible Names)';