CREATE TABLE IF NOT EXISTS `Property_MF_4_visible` (
  `SystemID` INT PRIMARY KEY COMMENT 'SystemID',
  `Class` VARCHAR(50) COMMENT 'Class',
  `Type` VARCHAR(50) COMMENT 'Type',
  `Area` VARCHAR(50) COMMENT 'Area',
  `SearchPrice` INT COMMENT 'Search Price',
  `AskingPrice` INT COMMENT 'Asking Price',
  `AddressNumber` TEXT COMMENT 'Address Number',
  `AddressSearchNumber` INT COMMENT 'Address Search Number',
  `AddressDirection` TEXT COMMENT 'Address Direction',
  `AddressStreet` TEXT COMMENT 'Address Street',
  `Address2` TEXT COMMENT 'Address 2',
  `City` TEXT COMMENT 'City',
  `State` VARCHAR(50) COMMENT 'State',
  `Zip` TEXT COMMENT 'Zip',
  `StatusCategory` VARCHAR(50) COMMENT 'Status Category',
  `StatusDetail` TEXT COMMENT 'Status Detail',
  `SaleRent` VARCHAR(50) COMMENT 'Sale/Rent',
  `View` VARCHAR(50) COMMENT 'View',
  `Levels` VARCHAR(50) COMMENT 'Levels',
  `GarageParking` VARCHAR(50) COMMENT 'Garage/Parking',
  `GarageCapacity` INT COMMENT 'Garage Capacity',
  `Terms` VARCHAR(50) COMMENT 'Terms',
  `SqFtPerUnit` VARCHAR(50) COMMENT 'Sq Ft Per Unit',
  `PavedStreets` VARCHAR(50) COMMENT 'Paved Streets',
  `Acres` DECIMAL(10,2) COMMENT 'Number of Acres',
  `Units` INT COMMENT 'Number of Units',
  `Agent` INT COMMENT 'Agent',
  `ListingOffice1` INT COMMENT 'Listing Office 1',
  `ListingAgent2` INT COMMENT 'Listing Agent 2',
  `ListingOffice2` INT COMMENT 'Listing Office 2',
  `ListingDate` DATE default '0000-00-00' NOT NULL COMMENT 'Listing Date',
  `ExpirationDate` DATE default '0000-00-00' NOT NULL COMMENT 'Expiration Date',
  `OriginalPrice` INT COMMENT 'Original Price',
  `HowSold` VARCHAR(50) COMMENT 'How Sold',
  `ContractDate` DATE default '0000-00-00' NOT NULL COMMENT 'Contract Date',
  `ClosingDate` DATE default '0000-00-00' NOT NULL COMMENT 'Closing Date',
  `SoldPrice` INT COMMENT 'Sold Price',
  `SellingAgent1` INT COMMENT 'Selling Agent 1',
  `SellingOffice1` INT COMMENT 'Selling Office 1',
  `SellingAgent2` INT COMMENT 'Selling Agent 2',
  `SellingOffice2` INT COMMENT 'Selling Office 2',
  `HotSheetDate` DATE default '0000-00-00' NOT NULL COMMENT 'HotSheet Date',
  `StatusDate` DATE default '0000-00-00' NOT NULL COMMENT 'Status Date',
  `PriceDate` DATE default '0000-00-00' NOT NULL COMMENT 'Price Date',
  `InputDate` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'Input Date',
  `UpdateDate` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'Update Date',
  `PhotoCount` INT COMMENT 'Photo Count',
  `PhotoTimestamp` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'PhotoTimestamp',
  `OffMarketDate` DATE default '0000-00-00' NOT NULL COMMENT 'Off Market Date',
  `AssociatedDocumentCount` INT COMMENT 'Associated Document Count',
  `MLS` TEXT COMMENT 'MLS #',
  `StreetDesignation` VARCHAR(50) COMMENT 'Street Designation',
  `GeoLatitude` DECIMAL(10,2) COMMENT 'Geo Latitude',
  `GeoLongitude` DECIMAL(10,2) COMMENT 'Geo Longitude',
  `GeoQuality` DECIMAL(10,2) COMMENT 'Geo Quality',
  `GeoZoomLevel` DECIMAL(10,2) COMMENT 'Geo Zoom Level',
  `GeoAddressLine` TEXT COMMENT 'Geo Address Line',
  `GeoPrimaryCity` TEXT COMMENT 'Geo Primary City',
  `GeoSecondaryCity` TEXT COMMENT 'Geo Secondary City',
  `GeoSubdivision` TEXT COMMENT 'Geo Subdivision',
  `GeoPostalCode` TEXT COMMENT 'Geo Postal Code',
  `GeoMatchCode` INT COMMENT 'Geo Match Code',
  `GeoMatchedMethod` INT COMMENT 'Geo Matched Method',
  `GeoUpdateTimestamp` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'Geo Update Timestamp',
  `FirstPhotoAddTimestamp` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'First Photo Add Timestamp',
  `OffMarketStatusDate` DATE default '0000-00-00' NOT NULL COMMENT 'Off Market Status Date',
  `LVTDate` DATE default '0000-00-00' NOT NULL COMMENT 'LVT Date',
  `Concessions` VARCHAR(50) COMMENT 'Concessions',
  `Address` TEXT COMMENT 'Address',
  `Status` VARCHAR(50) COMMENT 'Status',
  `DOM` INT COMMENT 'DOM',
  `DOMLS` INT COMMENT 'DOMLS',
  `CumulativeDOM` INT COMMENT 'Cumulative DOM',
  `BrokerAttribContact` TEXT COMMENT 'Broker Attrib Contact',
  `PavedStreetsYN` VARCHAR(50) COMMENT 'Paved Streets Y/N',
  `Subdivision` VARCHAR(50) COMMENT 'Subdivision',
  `SchoolDistrict` VARCHAR(50) COMMENT 'School District',
  `Foundation` VARCHAR(50) COMMENT 'Foundation',
  `WaterSewer` VARCHAR(50) COMMENT 'Water/Sewer',
  `FIPSCode` VARCHAR(50) COMMENT 'FIPS Code',
  `OffGridYN` VARCHAR(50) COMMENT 'Off Grid Y/N',
  `OwnerName` TEXT COMMENT 'Owner Name',
  `OwnerPhone` TEXT COMMENT 'Owner Phone',
  `Zoning` TEXT COMMENT 'Zoning',
  `ApproxLotDimensions` TEXT COMMENT 'Approx Lot Dimensions',
  `APN` TEXT COMMENT 'APN #',
  `County` VARCHAR(50) COMMENT 'County',
  `SaleIncluded` TEXT COMMENT 'Sale Included',
  `YearBuilt` INT COMMENT 'Year Built',
  `TotalSQFT` INT COMMENT 'Total SQ FT',
  `SoldPriceperSQFT` DECIMAL(10,2) COMMENT 'Sold Price per SQFT',
  `SellerConcessionsYN` VARCHAR(50) COMMENT 'Seller Concessions Y/N',
  `REOYN` VARCHAR(50) COMMENT 'REO Y/N',
  `ShortSale` VARCHAR(50) COMMENT 'Short Sale',
  `UnitASQFT` TEXT COMMENT 'Unit A SQFT',
  `UnitABedrooms` TEXT COMMENT 'Unit A Bedrooms',
  `UnitABathrooms` TEXT COMMENT 'Unit A Bathrooms',
  `UnitAMonthlyRent` TEXT COMMENT 'Unit A Monthly Rent',
  `UnitAOwnTenPaysUtil` VARCHAR(50) COMMENT 'Unit A Own/Ten Pays Util',
  `UnitBSQFT` TEXT COMMENT 'Unit B SQFT',
  `UnitBBedrooms` TEXT COMMENT 'Unit B Bedrooms',
  `UnitBBathrooms` TEXT COMMENT 'Unit B Bathrooms',
  `UnitBMonthlyRent` TEXT COMMENT 'Unit B Monthly Rent',
  `UnitBOwnTenPaysUtil` VARCHAR(50) COMMENT 'Unit B Own/Ten Pays Util',
  `UnitCSQFT` TEXT COMMENT 'Unit C SQFT',
  `UnitCBedrooms` TEXT COMMENT 'Unit C Bedrooms',
  `UnitCBathrooms` TEXT COMMENT 'Unit C Bathrooms',
  `UnitCMonthlyRent` TEXT COMMENT 'Unit C Monthly Rent',
  `UnitCOwnTenPaysUtil` VARCHAR(50) COMMENT 'Unit C Own/Ten Pays Util',
  `UnitDSQFT` TEXT COMMENT 'Unit D SQFT',
  `UnitDBedrooms` TEXT COMMENT 'Unit D Bedrooms',
  `UnitDBathrooms` TEXT COMMENT 'Unit D Bathrooms',
  `UnitDMonthlyRent` TEXT COMMENT 'Unit D Monthly Rent',
  `UnitDOwnTenPaysUtil` VARCHAR(50) COMMENT 'Unit D Own/Ten Pays Util',
  `UnitESQFT` TEXT COMMENT 'Unit E SQFT',
  `UnitEBedrooms` TEXT COMMENT 'Unit E Bedrooms',
  `UnitEBathrooms` TEXT COMMENT 'Unit E Bathrooms',
  `UnitEMonthlyRent` TEXT COMMENT 'Unit E Monthly Rent',
  `UnitEOwnTenPaysUtil` VARCHAR(50) COMMENT 'Unit E Own/Ten Pays Util',
  `UnitFSQFT` TEXT COMMENT 'Unit F SQFT',
  `UnitFBedrooms` TEXT COMMENT 'Unit F Bedrooms',
  `UnitFBathrooms` TEXT COMMENT 'Unit F Bathrooms',
  `UnitFMonthlyRent` TEXT COMMENT 'Unit F Monthly Rent',
  `UnitFOwnTenPaysUtil` VARCHAR(50) COMMENT 'Unit F Own/Ten Pays Util',
  `SellerConcessions` TEXT COMMENT 'Seller Concessions',
  `Directions` TEXT COMMENT 'Directions',
  `VirtualTour` TEXT COMMENT 'Virtual Tour',
  `DroneTour` TEXT COMMENT 'Drone Tour',
  `AgentHitCount` INT COMMENT 'Agent Hit Count',
  `ClientHitCount` INT COMMENT 'Client Hit Count',
  `TaxDatabaseID` INT COMMENT 'Tax Database ID',
  `TaxPropertyID` TEXT COMMENT 'Tax Property ID',
  `STYLESTORY` TEXT COMMENT 'STYLE/STORY',
  `INTERIORCONDITION` TEXT COMMENT 'INTERIOR CONDITION',
  `EXTERIORCONDITION` TEXT COMMENT 'EXTERIOR CONDITION',
  `AVAILABLEFINANCING` TEXT COMMENT 'AVAILABLE FINANCING',
  `MULTIFAMILYIN` TEXT COMMENT 'MULTI-FAMILY IN',
  `FOUNDATION` TEXT COMMENT 'FOUNDATION',
  `ROOF` TEXT COMMENT 'ROOF',
  `EXTERIOR` TEXT COMMENT 'EXTERIOR',
  `PROPERTYDESCRIPTION` TEXT COMMENT 'PROPERTY DESCRIPTION',
  `UTILITIES` TEXT COMMENT 'UTILITIES',
  `INTERIORFEATURES` TEXT COMMENT 'INTERIOR FEATURES',
  `APPLIANCES` TEXT COMMENT 'APPLIANCES',
  `HEATINGSYSTEM` TEXT COMMENT 'HEATING SYSTEM',
  `STREETROADINFORMATION` TEXT COMMENT 'STREET/ROAD INFORMATION',
  `AGENTINFORMATION` TEXT COMMENT 'AGENT INFORMATION',
  `CLOSINGPOSSESSION` TEXT COMMENT 'CLOSING/POSSESSION',
  `INTERNET` TEXT COMMENT 'INTERNET',
  `AgentOnlyRemarks` TEXT COMMENT 'Agent Only Remarks',
  `PublicRemarks` TEXT COMMENT 'Public Remarks',
  `LA1AgentLogonName` TEXT COMMENT 'LA1Agent Logon Name',
  `LA1AgentType` VARCHAR(50) COMMENT 'LA1Agent Type',
  `LA1AgentFirstName` TEXT COMMENT 'LA1Agent First Name',
  `LA1AgentLastName` TEXT COMMENT 'LA1Agent Last Name',
  `LA1AgentMiddleInitial` TEXT COMMENT 'LA1Agent Middle Initial',
  `LA1AgentAddressStreetName` TEXT COMMENT 'LA1Agent Address Street Name',
  `LA1AgentAddress2` TEXT COMMENT 'LA1Agent Address2',
  `LA1AgentCity` TEXT COMMENT 'LA1Agent City',
  `LA1AgentState` VARCHAR(50) COMMENT 'LA1Agent State',
  `LA1AgentZip` TEXT COMMENT 'LA1Agent Zip',
  `LA1AgentPhone1Description` TEXT COMMENT 'LA1Agent Phone1 Description',
  `LA1AgentPhone1CountryId` VARCHAR(50) COMMENT 'LA1Agent Phone1 CountryId',
  `LA1AgentPhone1Number` TEXT COMMENT 'LA1Agent Phone1 Number',
  `LA1AgentPhone1Extension` TEXT COMMENT 'LA1Agent Phone1 Extension',
  `LA1AgentPhone2Description` TEXT COMMENT 'LA1Agent Phone2 Description',
  `LA1AgentPhone2CountryId` VARCHAR(50) COMMENT 'LA1Agent Phone2 CountryId',
  `LA1AgentPhone2Number` TEXT COMMENT 'LA1Agent Phone2 Number',
  `LA1AgentPhone2Extension` TEXT COMMENT 'LA1Agent Phone2 Extension',
  `LA1AgentPhone3Description` TEXT COMMENT 'LA1Agent Phone3 Description',
  `LA1AgentPhone3CountryId` VARCHAR(50) COMMENT 'LA1Agent Phone3 CountryId',
  `LA1AgentPhone3Number` TEXT COMMENT 'LA1Agent Phone3 Number',
  `LA1AgentPhone3Extension` TEXT COMMENT 'LA1Agent Phone3 Extension',
  `LA1AgentPhone4Description` TEXT COMMENT 'LA1Agent Phone4 Description',
  `LA1AgentPhone4CountryId` VARCHAR(50) COMMENT 'LA1Agent Phone4 CountryId',
  `LA1AgentPhone4Number` TEXT COMMENT 'LA1Agent Phone4 Number',
  `LA1AgentPhone4Extension` TEXT COMMENT 'LA1Agent Phone4 Extension',
  `LA1AgentPhone5Description` TEXT COMMENT 'LA1Agent Phone5 Description',
  `LA1AgentPhone5CountryId` VARCHAR(50) COMMENT 'LA1Agent Phone5 CountryId',
  `LA1AgentPhone5Number` TEXT COMMENT 'LA1Agent Phone5 Number',
  `LA1AgentPhone5Extension` TEXT COMMENT 'LA1Agent Phone5 Extension',
  `LA1AgentEmail` TEXT COMMENT 'LA1Agent Email',
  `LA1AgentUrl` TEXT COMMENT 'LA1Agent Url',
  `LA1AgentStatus` VARCHAR(50) COMMENT 'LA1Agent Status',
  `LA1UserCode` TEXT COMMENT 'LA1User Code',
  `LA2AgentType` VARCHAR(50) COMMENT 'LA2Agent Type',
  `LA2AgentFirstName` TEXT COMMENT 'LA2Agent First Name',
  `LA2AgentLastName` TEXT COMMENT 'LA2Agent Last Name',
  `LA2AgentMiddleInitial` TEXT COMMENT 'LA2Agent Middle Initial',
  `LA2AgentAddressStreetName` TEXT COMMENT 'LA2Agent Address Street Name',
  `LA2AgentAddress2` TEXT COMMENT 'LA2Agent Address2',
  `LA2AgentCity` TEXT COMMENT 'LA2Agent City',
  `LA2AgentState` VARCHAR(50) COMMENT 'LA2Agent State',
  `LA2AgentZip` TEXT COMMENT 'LA2Agent Zip',
  `LA2AgentPhone1Description` TEXT COMMENT 'LA2Agent Phone1 Description',
  `LA2AgentPhone1CountryId` VARCHAR(50) COMMENT 'LA2Agent Phone1 CountryId',
  `LA2AgentPhone1Number` TEXT COMMENT 'LA2Agent Phone1 Number',
  `LA2AgentPhone1Extension` TEXT COMMENT 'LA2Agent Phone1 Extension',
  `LA2AgentPhone2Description` TEXT COMMENT 'LA2Agent Phone2 Description',
  `LA2AgentPhone2CountryId` VARCHAR(50) COMMENT 'LA2Agent Phone2 CountryId',
  `LA2AgentPhone2Number` TEXT COMMENT 'LA2Agent Phone2 Number',
  `LA2AgentPhone2Extension` TEXT COMMENT 'LA2Agent Phone2 Extension',
  `LA2AgentPhone3Description` TEXT COMMENT 'LA2Agent Phone3 Description',
  `LA2AgentPhone3CountryId` VARCHAR(50) COMMENT 'LA2Agent Phone3 CountryId',
  `LA2AgentPhone3Number` TEXT COMMENT 'LA2Agent Phone3 Number',
  `LA2AgentPhone3Extension` TEXT COMMENT 'LA2Agent Phone3 Extension',
  `LA2AgentPhone4Description` TEXT COMMENT 'LA2Agent Phone4 Description',
  `LA2AgentPhone4CountryId` VARCHAR(50) COMMENT 'LA2Agent Phone4 CountryId',
  `LA2AgentPhone4Number` TEXT COMMENT 'LA2Agent Phone4 Number',
  `LA2AgentPhone4Extension` TEXT COMMENT 'LA2Agent Phone4 Extension',
  `LA2AgentPhone5Description` TEXT COMMENT 'LA2Agent Phone5 Description',
  `LA2AgentPhone5CountryId` VARCHAR(50) COMMENT 'LA2Agent Phone5 CountryId',
  `LA2AgentPhone5Number` TEXT COMMENT 'LA2Agent Phone5 Number',
  `LA2AgentPhone5Extension` TEXT COMMENT 'LA2Agent Phone5 Extension',
  `LA2AgentEmail` TEXT COMMENT 'LA2Agent Email',
  `LA2AgentUrl` TEXT COMMENT 'LA2Agent Url',
  `LA2AgentStatus` VARCHAR(50) COMMENT 'LA2Agent Status',
  `SA1AgentLogonName` TEXT COMMENT 'SA1Agent Logon Name',
  `SA1AgentType` VARCHAR(50) COMMENT 'SA1Agent Type',
  `SA1AgentFirstName` TEXT COMMENT 'SA1Agent First Name',
  `SA1AgentLastName` TEXT COMMENT 'SA1Agent Last Name',
  `SA1AgentMiddleInitial` TEXT COMMENT 'SA1Agent Middle Initial',
  `SA1AgentAddressStreetName` TEXT COMMENT 'SA1Agent Address Street Name',
  `SA1AgentAddress2` TEXT COMMENT 'SA1Agent Address2',
  `SA1AgentCity` TEXT COMMENT 'SA1Agent City',
  `SA1AgentState` VARCHAR(50) COMMENT 'SA1Agent State',
  `SA1AgentZip` TEXT COMMENT 'SA1Agent Zip',
  `SA1AgentPhone1Description` TEXT COMMENT 'SA1Agent Phone1 Description',
  `SA1AgentPhone1CountryId` VARCHAR(50) COMMENT 'SA1Agent Phone1 CountryId',
  `SA1AgentPhone1Number` TEXT COMMENT 'SA1Agent Phone1 Number',
  `SA1AgentPhone1Extension` TEXT COMMENT 'SA1Agent Phone1 Extension',
  `SA1AgentPhone2Description` TEXT COMMENT 'SA1Agent Phone2 Description',
  `SA1AgentPhone2CountryId` VARCHAR(50) COMMENT 'SA1Agent Phone2 CountryId',
  `SA1AgentPhone2Number` TEXT COMMENT 'SA1Agent Phone2 Number',
  `SA1AgentPhone2Extension` TEXT COMMENT 'SA1Agent Phone2 Extension',
  `SA1AgentPhone3Description` TEXT COMMENT 'SA1Agent Phone3 Description',
  `SA1AgentPhone3CountryId` VARCHAR(50) COMMENT 'SA1Agent Phone3 CountryId',
  `SA1AgentPhone3Number` TEXT COMMENT 'SA1Agent Phone3 Number',
  `SA1AgentPhone3Extension` TEXT COMMENT 'SA1Agent Phone3 Extension',
  `SA1AgentPhone4Description` TEXT COMMENT 'SA1Agent Phone4 Description',
  `SA1AgentPhone4CountryId` VARCHAR(50) COMMENT 'SA1Agent Phone4 CountryId',
  `SA1AgentPhone4Number` TEXT COMMENT 'SA1Agent Phone4 Number',
  `SA1AgentPhone4Extension` TEXT COMMENT 'SA1Agent Phone4 Extension',
  `SA1AgentPhone5Description` TEXT COMMENT 'SA1Agent Phone5 Description',
  `SA1AgentPhone5CountryId` VARCHAR(50) COMMENT 'SA1Agent Phone5 CountryId',
  `SA1AgentPhone5Number` TEXT COMMENT 'SA1Agent Phone5 Number',
  `SA1AgentPhone5Extension` TEXT COMMENT 'SA1Agent Phone5 Extension',
  `SA1AgentEmail` TEXT COMMENT 'SA1Agent Email',
  `SA1AgentUrl` TEXT COMMENT 'SA1Agent Url',
  `SA1AgentStatus` VARCHAR(50) COMMENT 'SA1Agent Status',
  `SA2AgentType` VARCHAR(50) COMMENT 'SA2Agent Type',
  `SA2AgentFirstName` TEXT COMMENT 'SA2Agent First Name',
  `SA2AgentLastName` TEXT COMMENT 'SA2Agent Last Name',
  `SA2AgentMiddleInitial` TEXT COMMENT 'SA2Agent Middle Initial',
  `SA2AgentAddressStreetName` TEXT COMMENT 'SA2Agent Address Street Name',
  `SA2AgentAddress2` TEXT COMMENT 'SA2Agent Address2',
  `SA2AgentCity` TEXT COMMENT 'SA2Agent City',
  `SA2AgentState` VARCHAR(50) COMMENT 'SA2Agent State',
  `SA2AgentZip` TEXT COMMENT 'SA2Agent Zip',
  `SA2AgentPhone1Description` TEXT COMMENT 'SA2Agent Phone1 Description',
  `SA2AgentPhone1CountryId` VARCHAR(50) COMMENT 'SA2Agent Phone1 CountryId',
  `SA2AgentPhone1Number` TEXT COMMENT 'SA2Agent Phone1 Number',
  `SA2AgentPhone1Extension` TEXT COMMENT 'SA2Agent Phone1 Extension',
  `SA2AgentPhone2Description` TEXT COMMENT 'SA2Agent Phone2 Description',
  `SA2AgentPhone2CountryId` VARCHAR(50) COMMENT 'SA2Agent Phone2 CountryId',
  `SA2AgentPhone2Number` TEXT COMMENT 'SA2Agent Phone2 Number',
  `SA2AgentPhone2Extension` TEXT COMMENT 'SA2Agent Phone2 Extension',
  `SA2AgentPhone3Description` TEXT COMMENT 'SA2Agent Phone3 Description',
  `SA2AgentPhone3CountryId` VARCHAR(50) COMMENT 'SA2Agent Phone3 CountryId',
  `SA2AgentPhone3Number` TEXT COMMENT 'SA2Agent Phone3 Number',
  `SA2AgentPhone3Extension` TEXT COMMENT 'SA2Agent Phone3 Extension',
  `SA2AgentPhone4Description` TEXT COMMENT 'SA2Agent Phone4 Description',
  `SA2AgentPhone4CountryId` VARCHAR(50) COMMENT 'SA2Agent Phone4 CountryId',
  `SA2AgentPhone4Number` TEXT COMMENT 'SA2Agent Phone4 Number',
  `SA2AgentPhone4Extension` TEXT COMMENT 'SA2Agent Phone4 Extension',
  `SA2AgentPhone5Description` TEXT COMMENT 'SA2Agent Phone5 Description',
  `SA2AgentPhone5CountryId` VARCHAR(50) COMMENT 'SA2Agent Phone5 CountryId',
  `SA2AgentPhone5Number` TEXT COMMENT 'SA2Agent Phone5 Number',
  `SA2AgentPhone5Extension` TEXT COMMENT 'SA2Agent Phone5 Extension',
  `SA2AgentEmail` TEXT COMMENT 'SA2Agent Email',
  `SA2AgentUrl` TEXT COMMENT 'SA2Agent Url',
  `SA2AgentStatus` VARCHAR(50) COMMENT 'SA2Agent Status',
  `LO1OfficeIdentifier` INT COMMENT 'LO1Office Identifier',
  `LO1MainOfficeID` INT COMMENT 'LO1Main Office ID',
  `LO1OfficeType` VARCHAR(50) COMMENT 'LO1Office Type',
  `LO1OfficeAbbreviation` TEXT COMMENT 'LO1Office Abbreviation',
  `LO1OfficeName` TEXT COMMENT 'LO1Office Name',
  `LO1OffceAddressStreetName` TEXT COMMENT 'LO1Offce Address Street Name',
  `LO1OfficeAddress2` TEXT COMMENT 'LO1Office Address2',
  `LO1OfficeCity` TEXT COMMENT 'LO1Office City',
  `LO1OfficeState` VARCHAR(50) COMMENT 'LO1Office State',
  `LO1OfficeZip` TEXT COMMENT 'LO1Office Zip',
  `LO1OfficePhone1Description` TEXT COMMENT 'LO1Office Phone1 Description',
  `LO1OfficePhone1CountryId` VARCHAR(50) COMMENT 'LO1Office Phone1 CountryId',
  `LO1OfficePhone1Number` TEXT COMMENT 'LO1Office Phone1 Number',
  `LO1OfficePhone1Extension` TEXT COMMENT 'LO1Office Phone1 Extension',
  `LO1OfficeEmail` TEXT COMMENT 'LO1Office Email',
  `LO1OfficeUrl` TEXT COMMENT 'LO1Office Url',
  `LO1BoardID` INT COMMENT 'LO1Board ID',
  `LO2OfficeIdentifier` INT COMMENT 'LO2Office Identifier',
  `LO2MainOfficeID` INT COMMENT 'LO2Main Office ID',
  `LO2OfficeType` VARCHAR(50) COMMENT 'LO2Office Type',
  `LO2OfficeAbbreviation` TEXT COMMENT 'LO2Office Abbreviation',
  `LO2OfficeName` TEXT COMMENT 'LO2Office Name',
  `LO2OffceAddressStreetName` TEXT COMMENT 'LO2Offce Address Street Name',
  `LO2OfficeAddress2` TEXT COMMENT 'LO2Office Address2',
  `LO2OfficeCity` TEXT COMMENT 'LO2Office City',
  `LO2OfficeState` VARCHAR(50) COMMENT 'LO2Office State',
  `LO2OfficeZip` TEXT COMMENT 'LO2Office Zip',
  `LO2OfficePhone1Description` TEXT COMMENT 'LO2Office Phone1 Description',
  `LO2OfficePhone1CountryId` VARCHAR(50) COMMENT 'LO2Office Phone1 CountryId',
  `LO2OfficePhone1Number` TEXT COMMENT 'LO2Office Phone1 Number',
  `LO2OfficePhone1Extension` TEXT COMMENT 'LO2Office Phone1 Extension',
  `LO2OfficeEmail` TEXT COMMENT 'LO2Office Email',
  `LO2OfficeUrl` TEXT COMMENT 'LO2Office Url',
  `LO2BoardID` INT COMMENT 'LO2Board ID',
  `SO1OfficeIdentifier` INT COMMENT 'SO1Office Identifier',
  `SO1MainOfficeID` INT COMMENT 'SO1Main Office ID',
  `SO1OfficeType` VARCHAR(50) COMMENT 'SO1Office Type',
  `SO1OfficeAbbreviation` TEXT COMMENT 'SO1Office Abbreviation',
  `SO1OfficeName` TEXT COMMENT 'SO1Office Name',
  `SO1OffceAddressStreetName` TEXT COMMENT 'SO1Offce Address Street Name',
  `SO1OfficeAddress2` TEXT COMMENT 'SO1Office Address2',
  `SO1OfficeCity` TEXT COMMENT 'SO1Office City',
  `SO1OfficeState` VARCHAR(50) COMMENT 'SO1Office State',
  `SO1OfficeZip` TEXT COMMENT 'SO1Office Zip',
  `SO1OfficePhone1Description` TEXT COMMENT 'SO1Office Phone1 Description',
  `SO1OfficePhone1CountryId` VARCHAR(50) COMMENT 'SO1Office Phone1 CountryId',
  `SO1OfficePhone1Number` TEXT COMMENT 'SO1Office Phone1 Number',
  `SO1OfficePhone1Extension` TEXT COMMENT 'SO1Office Phone1 Extension',
  `SO1OfficeEmail` TEXT COMMENT 'SO1Office Email',
  `SO1OfficeUrl` TEXT COMMENT 'SO1Office Url',
  `SO1BoardID` INT COMMENT 'SO1Board ID',
  `SO2OfficeIdentifier` INT COMMENT 'SO2Office Identifier',
  `SO2MainOfficeID` INT COMMENT 'SO2Main Office ID',
  `SO2OfficeType` VARCHAR(50) COMMENT 'SO2Office Type',
  `SO2OfficeAbbreviation` TEXT COMMENT 'SO2Office Abbreviation',
  `SO2OfficeName` TEXT COMMENT 'SO2Office Name',
  `SO2OffceAddressStreetName` TEXT COMMENT 'SO2Offce Address Street Name',
  `SO2OfficeAddress2` TEXT COMMENT 'SO2Office Address2',
  `SO2OfficeCity` TEXT COMMENT 'SO2Office City',
  `SO2OfficeState` VARCHAR(50) COMMENT 'SO2Office State',
  `SO2OfficeZip` TEXT COMMENT 'SO2Office Zip',
  `SO2OfficePhone1Description` TEXT COMMENT 'SO2Office Phone1 Description',
  `SO2OfficePhone1CountryId` VARCHAR(50) COMMENT 'SO2Office Phone1 CountryId',
  `SO2OfficePhone1Number` TEXT COMMENT 'SO2Office Phone1 Number',
  `SO2OfficePhone1Extension` TEXT COMMENT 'SO2Office Phone1 Extension',
  `SO2OfficeEmail` TEXT COMMENT 'SO2Office Email',
  `SO2OfficeUrl` TEXT COMMENT 'SO2Office Url',
  `SO2BoardID` INT COMMENT 'SO2Board ID',
  `VOWInclude` VARCHAR(50) COMMENT 'VOW Include',
  `VOWAddress` VARCHAR(50) COMMENT 'VOW Address',
  `VOWComment` VARCHAR(50) COMMENT 'VOW Comment',
  `VOWAVM` VARCHAR(50) COMMENT 'VOW AVM',
  `IDXInclude` VARCHAR(50) COMMENT 'IDX Include',
  `DocTimestamp` DATETIME default '0000-00-00 00:00:00' NOT NULL COMMENT 'Doc Timestamp'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT 'All Property Listings - MULTI-FAMILY (Visible Names)';